nombre_empresa: "InnovaSys"
apache_index_dest: /var/www/html/index.html
samba_share_name: "Proyectos"
samba_share_path: "/srv/samba/proyectos"
samba_group: "desarrolladores"
samba_user: "devuser1"
samba_password: "Innova.2025"
samba_dir_mode: "2770"
samba_dir_mask: "0770"
samba_file_mask: "0660"
